"""Redis caching service for query results."""
import redis.asyncio as redis
import hashlib
import json
import logging
from typing import Optional, Any, Dict
from datetime import timedelta

from app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


class RedisService:
    """
    Redis caching service for query results.

    Provides:
    - Query result caching with TTL
    - Cache key generation from query + params
    - Cache invalidation
    - Connection health checks
    """

    def __init__(self):
        self.client: Optional[redis.Redis] = None
        self._connection_params = self._build_connection_params()

    def _build_connection_params(self) -> Dict[str, Any]:
        """Build Redis connection parameters from settings."""
        params = {
            "host": settings.REDIS_HOST,
            "port": settings.REDIS_PORT,
            "db": settings.REDIS_DB,
            "decode_responses": True,  # Auto-decode bytes to strings
            "socket_connect_timeout": 5,
            "socket_timeout": 5,
            "retry_on_timeout": True,
            "health_check_interval": 30,
        }

        if settings.REDIS_PASSWORD:
            params["password"] = settings.REDIS_PASSWORD

        return params

    async def connect(self):
        """Initialize Redis connection."""
        if self.client is not None:
            logger.warning("Redis client already connected")
            return

        try:
            self.client = redis.Redis(**self._connection_params)

            # Test connection
            await self.client.ping()
            logger.info(
                f"Redis connected successfully "
                f"(host={settings.REDIS_HOST}:{settings.REDIS_PORT}, "
                f"db={settings.REDIS_DB})"
            )

        except redis.ConnectionError as e:
            logger.error(f"Failed to connect to Redis: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error connecting to Redis: {e}")
            raise

    async def disconnect(self):
        """Close Redis connection gracefully."""
        if self.client:
            await self.client.close()
            logger.info("Redis connection closed")
            self.client = None

    def generate_cache_key(
        self,
        query: str,
        params: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate cache key from query and parameters.

        Args:
            query: SQL query or identifier
            params: Optional query parameters

        Returns:
            Cache key in format: "query_cache:{hash}"
        """
        # Combine query and params into a single string
        cache_input = query

        if params:
            # Sort params for consistent hashing
            sorted_params = json.dumps(params, sort_keys=True)
            cache_input = f"{query}:{sorted_params}"

        # Generate SHA256 hash
        cache_hash = hashlib.sha256(cache_input.encode()).hexdigest()

        # Use first 16 characters of hash for readability
        cache_key = f"query_cache:{cache_hash[:16]}"

        logger.debug(f"Generated cache key: {cache_key}")
        return cache_key

    async def get_cached_result(self, cache_key: str) -> Optional[Any]:
        """
        Retrieve cached query result.

        Args:
            cache_key: Cache key generated by generate_cache_key()

        Returns:
            Cached result (deserialized from JSON), or None if not found
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return None

        try:
            cached_data = await self.client.get(cache_key)

            if cached_data is None:
                logger.debug(f"Cache MISS: {cache_key}")
                return None

            # Deserialize JSON
            result = json.loads(cached_data)
            logger.info(f"Cache HIT: {cache_key}")
            return result

        except json.JSONDecodeError as e:
            logger.error(f"Error decoding cached data: {e}")
            # Delete corrupted cache entry
            await self.client.delete(cache_key)
            return None

        except redis.RedisError as e:
            logger.error(f"Redis error retrieving cache: {e}")
            return None

        except Exception as e:
            logger.error(f"Unexpected error retrieving cache: {e}")
            return None

    async def cache_result(
        self,
        cache_key: str,
        result: Any,
        ttl: Optional[int] = None
    ):
        """
        Cache query result with TTL.

        Args:
            cache_key: Cache key
            result: Result to cache (will be JSON-serialized)
            ttl: Time-to-live in seconds (default: REDIS_CACHE_TTL from settings)
        """
        if self.client is None:
            logger.warning("Redis client not initialized, skipping cache")
            return

        if not settings.ENABLE_QUERY_CACHING:
            logger.debug("Query caching disabled, skipping")
            return

        try:
            # Use default TTL if not specified
            ttl = ttl or settings.REDIS_CACHE_TTL

            # Serialize result to JSON
            cached_data = json.dumps(result)

            # Store in Redis with TTL
            await self.client.setex(
                cache_key,
                timedelta(seconds=ttl),
                cached_data
            )

            logger.info(f"Cached result: {cache_key} (TTL={ttl}s)")

        except (TypeError, ValueError) as e:
            logger.error(f"Error serializing result to JSON: {e}")
            # Don't cache if serialization fails

        except redis.RedisError as e:
            logger.error(f"Redis error caching result: {e}")

        except Exception as e:
            logger.error(f"Unexpected error caching result: {e}")

    async def invalidate_cache(self, pattern: str):
        """
        Invalidate cache entries matching pattern.

        Args:
            pattern: Redis key pattern (e.g., "query_cache:*")

        Example:
            await redis.invalidate_cache("query_cache:*")  # Clear all query caches
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return

        try:
            # Find all keys matching pattern
            keys = []
            async for key in self.client.scan_iter(match=pattern):
                keys.append(key)

            if keys:
                # Delete all matching keys
                await self.client.delete(*keys)
                logger.info(f"Invalidated {len(keys)} cache entries matching: {pattern}")
            else:
                logger.info(f"No cache entries found matching: {pattern}")

        except redis.RedisError as e:
            logger.error(f"Redis error invalidating cache: {e}")

        except Exception as e:
            logger.error(f"Unexpected error invalidating cache: {e}")

    async def clear_all_cache(self):
        """
        Clear all cache entries (use with caution!).

        This deletes ALL keys in the configured Redis database.
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return

        try:
            await self.client.flushdb()
            logger.warning("All cache entries cleared from Redis")

        except redis.RedisError as e:
            logger.error(f"Redis error clearing cache: {e}")

        except Exception as e:
            logger.error(f"Unexpected error clearing cache: {e}")

    async def get_cache_stats(self) -> Dict[str, Any]:
        """
        Get cache statistics.

        Returns:
            Dictionary with cache stats (keys count, memory usage, etc.)
        """
        if self.client is None:
            return {"status": "not_connected"}

        try:
            info = await self.client.info()

            # Count query cache keys
            query_cache_count = 0
            async for _ in self.client.scan_iter(match="query_cache:*"):
                query_cache_count += 1

            return {
                "status": "connected",
                "total_keys": info.get('db0', {}).get('keys', 0),
                "query_cache_keys": query_cache_count,
                "used_memory": info.get('used_memory_human', 'unknown'),
                "used_memory_peak": info.get('used_memory_peak_human', 'unknown'),
                "connected_clients": info.get('connected_clients', 0),
                "uptime_days": info.get('uptime_in_days', 0),
            }

        except redis.RedisError as e:
            logger.error(f"Redis error getting stats: {e}")
            return {"status": "error", "error": str(e)}

        except Exception as e:
            logger.error(f"Unexpected error getting cache stats: {e}")
            return {"status": "error", "error": str(e)}

    async def health_check(self) -> bool:
        """
        Check Redis connection health.

        Returns:
            True if healthy, False otherwise
        """
        if self.client is None:
            logger.error("Health check failed: Redis client not initialized")
            return False

        try:
            response = await self.client.ping()
            if response:
                logger.debug("Redis health check passed")
                return True
            else:
                logger.error("Redis health check failed: ping returned False")
                return False

        except redis.RedisError as e:
            logger.error(f"Redis health check failed: {e}")
            return False

        except Exception as e:
            logger.error(f"Unexpected error in health check: {e}")
            return False

    async def set_key(self, key: str, value: Any, ttl: Optional[int] = None):
        """
        Set a key-value pair in Redis.

        Args:
            key: Cache key
            value: Value to store (will be JSON-serialized)
            ttl: Time-to-live in seconds (optional)
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return

        try:
            value_json = json.dumps(value)

            if ttl:
                await self.client.setex(key, timedelta(seconds=ttl), value_json)
            else:
                await self.client.set(key, value_json)

            logger.debug(f"Set key: {key}")

        except Exception as e:
            logger.error(f"Error setting key {key}: {e}")

    async def get_key(self, key: str) -> Optional[Any]:
        """
        Get a value from Redis by key.

        Args:
            key: Cache key

        Returns:
            Deserialized value, or None if not found
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return None

        try:
            value = await self.client.get(key)

            if value is None:
                return None

            return json.loads(value)

        except Exception as e:
            logger.error(f"Error getting key {key}: {e}")
            return None

    async def delete_key(self, key: str):
        """
        Delete a key from Redis.

        Args:
            key: Cache key to delete
        """
        if self.client is None:
            logger.warning("Redis client not initialized")
            return

        try:
            await self.client.delete(key)
            logger.debug(f"Deleted key: {key}")

        except Exception as e:
            logger.error(f"Error deleting key {key}: {e}")
