"""Response models for API endpoints."""
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class GenieResponse(BaseModel):
    """Response model for Genie chat queries."""

    conversation_id: str = Field(
        ...,
        description="The conversation ID for follow-up queries",
    )
    message_id: str = Field(
        ...,
        description="The message ID",
    )
    response: str = Field(
        ...,
        description="The text response from Genie",
    )
    sql_query: Optional[str] = Field(
        None,
        description="The SQL query generated by Genie",
    )
    data: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Query result data",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="Column names for the query result",
    )
    visualization: Optional[Dict[str, Any]] = Field(
        None,
        description="Visualization configuration if available",
    )
    thinking_steps: Optional[List[str]] = Field(
        None,
        description="Genie's reasoning steps",
    )
    status: str = Field(
        ...,
        description="Message status (COMPLETED, FAILED, etc.)",
    )
    success: bool = Field(
        ...,
        description="Whether the query was successful",
    )
    error: Optional[str] = Field(
        None,
        description="Error message if query failed",
    )
    truncated: bool = Field(
        default=False,
        description="Whether results were truncated (> 5000 rows)",
    )


class ConversationMessage(BaseModel):
    """Model for a single conversation message."""

    message_id: str
    role: str  # 'user' or 'assistant'
    content: str
    sql_query: Optional[str] = None
    data: Optional[List[Dict[str, Any]]] = None
    timestamp: Optional[str] = None


class ConversationHistoryResponse(BaseModel):
    """Response model for conversation history."""

    conversation_id: str
    messages: List[ConversationMessage]
    success: bool


class KPIData(BaseModel):
    """KPI data for executive dashboard."""

    total_sales: float = Field(..., description="Total sales value")
    active_customers: int = Field(..., description="Number of active customers")
    opportunity_value: float = Field(..., description="Total opportunity value")
    critical_gaps: int = Field(..., description="Number of critical stock gaps")
    sales_trend: Optional[List[Dict[str, Any]]] = Field(
        None, description="Sales trend data"
    )
    period: str = Field(..., description="Time period for the data")


class OpportunityData(BaseModel):
    """Stock opportunity data."""

    customer_id: str
    customer_name: str
    product_id: str
    product_name: str
    brand: Optional[str] = None
    soh: float = Field(..., description="Stock on hand")
    dsoh_days: float = Field(..., description="Days stock on hand")
    avg_sales: Optional[float] = None
    opportunity_value: float = Field(..., description="Calculated opportunity value")
    region: Optional[str] = None
    territory: Optional[str] = None


class RepPerformanceData(BaseModel):
    """Rep performance metrics."""

    rep_id: str
    rep_name: str
    coverage_percent: float
    strike_rate: float
    total_calls: int
    territory: Optional[str] = None
    region: Optional[str] = None


class ProductPerformance(BaseModel):
    """Product performance data."""

    product_id: str
    product_name: str
    brand: str
    total_sales: float
    units_sold: int
    customer_count: int


class DashboardResponse(BaseModel):
    """Generic dashboard response wrapper."""

    dashboard_type: str = Field(
        ..., description="Type of dashboard (executive, manager, rep)"
    )
    data: Dict[str, Any] = Field(..., description="Dashboard data")
    success: bool = Field(..., description="Whether the query was successful")
    error: Optional[str] = Field(None, description="Error message if failed")


class ExecutiveDashboardResponse(BaseModel):
    """Executive dashboard specific response."""

    kpis: KPIData
    top_opportunities: List[OpportunityData]
    sales_trend: List[Dict[str, Any]]
    success: bool
    error: Optional[str] = None


class ManagerDashboardResponse(BaseModel):
    """Manager dashboard specific response."""

    territory_id: str
    product_performance: List[ProductPerformance]
    rep_performance: List[RepPerformanceData]
    opportunities: List[OpportunityData]
    success: bool
    error: Optional[str] = None


class RepDashboardResponse(BaseModel):
    """Rep dashboard specific response."""

    rep_id: str
    my_performance: Optional[RepPerformanceData]
    priority_opportunities: List[OpportunityData]
    all_opportunities: List[OpportunityData]
    success: bool
    error: Optional[str] = None


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(..., description="Overall health status")
    databricks_connected: bool = Field(
        ..., description="Whether Databricks is connected"
    )
    genie_available: bool = Field(..., description="Whether Genie is available")
    version: str = Field(..., description="API version")
    details: Optional[Dict[str, Any]] = Field(
        None, description="Additional health details"
    )
